### ISSUE TITLE
showButton属性不起作用

### ISSUE THREAD

**Issue by guangzezhu** [mizuka-wu/vue2-verify#18]

**Comment by guangzezhu** [comment]
额，学艺不精，自己的问题。。。
怎么撤销这个提问啊 ：）

**Comment by guangzezhu** [comment]
将showButton隐藏，如何知道验证码校验是否正确呢？
前端小白，success,ready事件属性怎么用
```
 <Verify  @success="smscodePass" :showButton="false"  :type="2"></Verify>

method: 
smscordPass() {
    this.flag=true;  //一直没有执行
}
```

**Comment by mizuka-wu** [comment]
> 将showButton隐藏，如何知道验证码校验是否正确呢？
> 前端小白，success,ready事件属性怎么用
> 
> ```
>  <Verify  @success="smscodePass" :showButton="false"  :type="2"></Verify>
> 
> method: 
> smscordPass() {
>     this.flag=true;  //一直没有执行
> }
> ```

...vue不是应该是methods: {}么
